BTC:
  outputs:
    dev:
      account: EZWUKBJ-GA39028
      database: BTC
      password: Akshay06101992
      role: ACCOUNTADMIN
      schema: DEV
      threads: 1
      type: snowflake
      user: akshaybudhanavar
      warehouse: COMPUTE_WH
  target: dev
