version: 2

sources:
  - name: STAGE
    database: BTC
    schema: STAGE
    tables:
      - name: BTC_TXN
        config:
          loaded_at_field: block_timestamp
          freshness:
            warn_after:
              count: 1
              period: minute
            error_after:
              count: 2
              period: minute
